id: type_assertions_quiz
learningObjectives:
  - Identify when to use type assertions in TypeScript.
hints:
  - Reviewing the [type assertion section](https://www.typescriptlang.org/docs/handbook/basic-types.html) might provide clarity.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Let's test your knowledge with a quick question on type assertions.
          - text: When would you typically use a type assertion in TypeScript?
    - actionId: quiz_message
      name: quiz
      params:
        person: lucca
        options:
          - To tell the compiler to trust you about a variable's type.
          - To convert a string to a number.
          - To handle null or undefined values safely.
trigger:
  type: chat_form_submitted
  flowNode:
    switch:
      key: ${formSubmission}
      cases:
        A:
          do:
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: Correct! Type assertions are there when you know more about a variable than TypeScript does.
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: ':tada: You''ve completed this part! Press ''Next'' to move on.'
            - actionId: finish_step
        B:
          do:
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: Not quite. Type assertions aren't for converting types, just asserting them.
            - actionId: replay_action
              params:
                actionName: quiz
        C:
          do:
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: That's not right. Handling null or undefined values is different from type assertions.
            - actionId: replay_action
              params:
                actionName: quiz
